/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Deliveries: () => import('#controllers/deliveries_controller'),
  Endpoints: () => import('#controllers/endpoints_controller'),
  Events: () => import('#controllers/events_controller'),
  Metrics: () => import('#controllers/metrics_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
